- set:
    system:
      aaa:
        user:
          admin:
            password: '*'
      config:
        auto-save:
          state: enabled
      date-time:
        timezone: Etc/UTC
      dns:
        server:
          8.8.8.8: {}
      ntp:
        server:
          ntp.ubuntu.com: {}
      security:
        password-hardening:
          state: disabled
