global(workDirectory="/var/spool/rsyslog")
module(load="imuxsock" SysSock.Name="/dev/log")

template(
    name="HttpZtpFileFormat"
    type="string"
    string="%timegenerated:::date-rfc3339% %hostname% %syslogtag%%msg%\n"
)

if $programname == "dhcpd" then {
    action(
        type="omfile"
        file="/var/log/http-ztp/dhcpd.log"
        template="HttpZtpFileFormat"
    )
    stop
}

action(
    type="omfile"
    file="/var/log/http-ztp/syslog"
    template="HttpZtpFileFormat"
)
