#!/usr/bin/env python3
"""Shared, bounded OpenSSH public-key selection and project publication.

This module never opens a private key for reading. A key generated by ssh-keygen
is staged under a private temporary directory and installed with no-replace
hard links, so a concurrent or pre-existing key is never overwritten.
"""

from __future__ import annotations

import base64
import hashlib
import os
from pathlib import Path
import secrets
import stat
import struct
import subprocess
import tempfile


PUBLIC_KEY_LIMIT = 64 * 1024
KEYGEN = Path("/usr/bin/ssh-keygen")
KEYGEN_COMMENTS = frozenset({"root@management-server", "operator@laptop"})
PROJECT_PUBLIC_NAMES = frozenset({"laptop.pub", "mgmt-server.pub"})


class SshKeyPreparationError(ValueError):
    """A public-key precondition or race failed closed."""


def public_key_identity_bytes(data: bytes) -> tuple[bytes, bytes]:
    """Identify a bounded static OpenSSH public line by its type and wire blob.

    Existing project static keys include ECDSA and FIDO security-key formats;
    host auto-selection remains limited separately to Ed25519 and RSA.
    """
    if not data or len(data) > PUBLIC_KEY_LIMIT or not data.endswith(b"\n"):
        raise SshKeyPreparationError("public key must be one bounded newline-terminated line")
    if b"\r" in data or b"\n" in data[:-1] or any(c < 32 or c == 127 for c in data[:-1]):
        raise SshKeyPreparationError("public key contains an unsafe character")
    fields = data[:-1].split(b" ", 2)
    if len(fields) < 2 or not fields[1]:
        raise SshKeyPreparationError("public key must include a type and base64 blob")
    algorithm, encoded = fields[:2]
    if algorithm not in (
        b"ssh-ed25519", b"ssh-rsa",
        b"ecdsa-sha2-nistp256", b"ecdsa-sha2-nistp384", b"ecdsa-sha2-nistp521",
        b"sk-ssh-ed25519@openssh.com", b"sk-ecdsa-sha2-nistp256@openssh.com",
    ):
        raise SshKeyPreparationError("unsupported public key type")
    try:
        blob = base64.b64decode(encoded, validate=True)
    except (ValueError, base64.binascii.Error) as exc:
        raise SshKeyPreparationError("invalid public key base64") from exc
    if base64.b64encode(blob) != encoded:
        raise SshKeyPreparationError("noncanonical public key base64")

    def field(offset: int) -> tuple[bytes, int]:
        if offset + 4 > len(blob):
            raise SshKeyPreparationError("truncated public key blob")
        length = struct.unpack_from(">I", blob, offset)[0]
        offset += 4
        if length > PUBLIC_KEY_LIMIT or offset + length > len(blob):
            raise SshKeyPreparationError("invalid public key blob length")
        return blob[offset:offset + length], offset + length

    blob_type, offset = field(0)
    if blob_type != algorithm:
        raise SshKeyPreparationError("public key type/blob mismatch")
    if algorithm == b"ssh-ed25519":
        key, offset = field(offset)
        if len(key) != 32:
            raise SshKeyPreparationError("Ed25519 key must contain 32 bytes")
    elif algorithm == b"ssh-rsa":
        exponent, offset = field(offset)
        modulus, offset = field(offset)
        if not exponent or not modulus:
            raise SshKeyPreparationError("RSA public exponent or modulus invalid")
    elif algorithm.startswith(b"ecdsa-sha2-"):
        curve, offset = field(offset)
        point, offset = field(offset)
        if algorithm != b"ecdsa-sha2-" + curve or not point:
            raise SshKeyPreparationError("ECDSA curve or point invalid")
    elif algorithm == b"sk-ssh-ed25519@openssh.com":
        key, offset = field(offset)
        application, offset = field(offset)
        if len(key) != 32 or not application:
            raise SshKeyPreparationError("security-key Ed25519 fields invalid")
    else:
        curve, offset = field(offset)
        point, offset = field(offset)
        application, offset = field(offset)
        if curve != b"nistp256" or not point or not application:
            raise SshKeyPreparationError("security-key ECDSA fields invalid")
    if offset != len(blob):
        raise SshKeyPreparationError("public key blob has trailing bytes")
    return algorithm, blob


_identity = public_key_identity_bytes


def _fingerprint(identity: tuple[bytes, bytes]) -> str:
    digest = hashlib.sha256(identity[1]).digest()
    return "SHA256:" + base64.b64encode(digest).rstrip(b"=").decode("ascii")


def _read_public(path: Path) -> tuple[bytes, os.stat_result]:
    flags = os.O_RDONLY | os.O_NOFOLLOW | getattr(os, "O_CLOEXEC", 0)
    fd = -1
    try:
        before = os.lstat(path)
        if not stat.S_ISREG(before.st_mode):
            raise SshKeyPreparationError(f"public key is not a regular no-follow file: {path}")
        fd = os.open(path, flags)
        held = os.fstat(fd)
        if not stat.S_ISREG(held.st_mode) or (
            held.st_dev, held.st_ino
        ) != (before.st_dev, before.st_ino):
            raise SshKeyPreparationError(f"public key changed during open: {path}")
        data = bytearray()
        while len(data) <= PUBLIC_KEY_LIMIT:
            part = os.read(fd, min(8192, PUBLIC_KEY_LIMIT + 1 - len(data)))
            if not part:
                break
            data.extend(part)
        if len(data) > PUBLIC_KEY_LIMIT:
            raise SshKeyPreparationError(f"public key too large: {path}")
        after = os.fstat(fd)
        named = os.lstat(path)
        if (
            (after.st_dev, after.st_ino, after.st_size, after.st_mtime_ns)
            != (held.st_dev, held.st_ino, held.st_size, held.st_mtime_ns)
            or (named.st_dev, named.st_ino) != (held.st_dev, held.st_ino)
        ):
            raise SshKeyPreparationError(f"public key changed during read: {path}")
        _identity(bytes(data))
        return bytes(data), held
    except OSError as exc:
        raise SshKeyPreparationError(f"cannot safely read public key {path}: {exc}") from exc
    finally:
        if fd >= 0:
            os.close(fd)


def public_key_identity(path: Path) -> tuple[bytes, bytes]:
    """Return type + SSH wire blob, deliberately ignoring the comment."""
    return _identity(_read_public(Path(path))[0])


def _ssh_directory(path: Path, *, create: bool) -> Path:
    path = Path(path)
    try:
        metadata = os.lstat(path)
    except FileNotFoundError:
        if not create:
            return path
        try:
            path.mkdir(mode=0o700)
        except OSError as exc:
            raise SshKeyPreparationError(f"cannot create SSH directory {path}: {exc}") from exc
        metadata = os.lstat(path)
    if not stat.S_ISDIR(metadata.st_mode) or metadata.st_uid != os.geteuid():
        raise SshKeyPreparationError("SSH directory must be an owned no-follow directory")
    if stat.S_IMODE(metadata.st_mode) & 0o077:
        raise SshKeyPreparationError("SSH directory must not be group/world accessible")
    return path


def select_public_key(ssh_dir: Path) -> Path | None:
    """Prefer id_ed25519.pub, then id_rsa.pub; private files are not candidates."""
    ssh_dir = _ssh_directory(Path(ssh_dir), create=False)
    if not ssh_dir.exists():
        return None
    for name, expected_type in (
        ("id_ed25519.pub", b"ssh-ed25519"), ("id_rsa.pub", b"ssh-rsa"),
    ):
        path = ssh_dir / name
        try:
            os.lstat(path)
        except FileNotFoundError:
            continue
        identity = public_key_identity(path)
        if identity[0] != expected_type:
            raise SshKeyPreparationError(f"{name} has the wrong public key type")
        return path
    return None


def generate_ed25519_pair(ssh_dir: Path, *, comment: str) -> Path:
    """Generate an Ed25519 pair without reading or overwriting a private file."""
    if comment not in KEYGEN_COMMENTS:
        raise SshKeyPreparationError("keygen comment must be a literal approved value")
    ssh_dir = _ssh_directory(Path(ssh_dir), create=True)
    private = ssh_dir / "id_ed25519"
    public = ssh_dir / "id_ed25519.pub"
    for path in (private, public):
        try:
            os.lstat(path)
        except FileNotFoundError:
            continue
        raise SshKeyPreparationError(f"key generation refuses existing target: {path}")
    if not KEYGEN.is_file():
        raise SshKeyPreparationError("fixed /usr/bin/ssh-keygen is unavailable")

    stage = Path(tempfile.mkdtemp(prefix=".ssh-key-prep-", dir=ssh_dir))
    staged_private = stage / "id_ed25519"
    staged_public = stage / "id_ed25519.pub"
    installed_private: tuple[int, int] | None = None
    try:
        try:
            result = subprocess.run(
                [str(KEYGEN), "-q", "-t", "ed25519", "-N", "", "-C", comment,
                 "-f", str(staged_private)],
                input=b"n\n", capture_output=True, timeout=20, check=False,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise SshKeyPreparationError(f"ssh-keygen failed: {exc}") from exc
        if result.returncode != 0:
            raise SshKeyPreparationError("ssh-keygen rejected Ed25519 generation")
        generated, _ = _read_public(staged_public)
        if _identity(generated)[0] != b"ssh-ed25519":
            raise SshKeyPreparationError("ssh-keygen did not produce Ed25519 public key")
        os.chmod(staged_private, 0o600, follow_symlinks=False)
        os.chmod(staged_public, 0o644, follow_symlinks=False)
        # link is no-replace for each final name. A second failure rolls back only
        # the inode we installed; no existing user's private key can be replaced.
        os.link(staged_private, private, follow_symlinks=False)
        held = os.lstat(private)
        installed_private = held.st_dev, held.st_ino
        os.link(staged_public, public, follow_symlinks=False)
        return public
    except OSError as exc:
        raise SshKeyPreparationError(f"cannot safely install generated key: {exc}") from exc
    finally:
        if installed_private is not None and not public.exists():
            try:
                named = os.lstat(private)
                if (named.st_dev, named.st_ino) == installed_private:
                    private.unlink()
            except FileNotFoundError:
                pass
        for path in (staged_public, staged_private):
            try:
                path.unlink()
            except FileNotFoundError:
                pass
        stage.rmdir()


def ensure_public_key(ssh_dir: Path, *, comment: str) -> Path:
    """Select an existing public key or generate Ed25519 when neither exists."""
    if comment not in KEYGEN_COMMENTS:
        raise SshKeyPreparationError("keygen comment must be a literal approved value")
    selected = select_public_key(ssh_dir)
    if selected is not None:
        return selected
    return generate_ed25519_pair(ssh_dir, comment=comment)


def _read_project_leaf(directory_fd: int, name: str) -> tuple[bytes, tuple[int, int]] | None:
    try:
        metadata = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
    except FileNotFoundError:
        return None
    if not stat.S_ISREG(metadata.st_mode) or metadata.st_nlink != 1:
        raise SshKeyPreparationError("project public key must be a single-link regular file")
    fd = -1
    try:
        fd = os.open(name, os.O_RDONLY | os.O_NOFOLLOW, dir_fd=directory_fd)
        held = os.fstat(fd)
        if (held.st_dev, held.st_ino) != (metadata.st_dev, metadata.st_ino):
            raise SshKeyPreparationError("project public key changed while opening")
        data = bytearray()
        while len(data) <= PUBLIC_KEY_LIMIT:
            part = os.read(fd, min(8192, PUBLIC_KEY_LIMIT + 1 - len(data)))
            if not part:
                break
            data.extend(part)
        if len(data) > PUBLIC_KEY_LIMIT:
            raise SshKeyPreparationError("project public key too large")
        return bytes(data), (held.st_dev, held.st_ino)
    except OSError as exc:
        raise SshKeyPreparationError(f"cannot safely read project public key: {exc}") from exc
    finally:
        if fd >= 0:
            os.close(fd)


def prepare_project_public_key(
    project: Path, destination_name: str, source: Path,
    *, expected_old_identity: tuple[int, int] | None = None,
    expected_source_identity: tuple[int, int] | None = None,
    on_mismatch: str = "reject",
) -> Path:
    """Publish an empty key, or explicitly rotate a mismatched real key.

    expected_old_identity lets a caller that already holds the old leaf (notably
    load) prove this is still that exact inode before publication.
    """
    if destination_name not in PROJECT_PUBLIC_NAMES:
        raise SshKeyPreparationError("destination must be a declared project public-key name")
    if on_mismatch not in ("reject", "replace"):
        raise SshKeyPreparationError("on_mismatch must be a literal reject or replace")
    project, source = Path(project), Path(source)
    source_data, source_stat = _read_public(source)
    if expected_source_identity is not None and (
        source_stat.st_dev, source_stat.st_ino
    ) != expected_source_identity:
        raise SshKeyPreparationError("held source public-key identity changed")
    new_identity = _identity(source_data)
    directory_fd = -1
    stage_fd = -1
    stage_name: str | None = None
    try:
        named_directory = os.lstat(project)
        if not stat.S_ISDIR(named_directory.st_mode):
            raise SshKeyPreparationError("project root must be a no-follow directory")
        directory_fd = os.open(project, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
        held_directory = os.fstat(directory_fd)
        if (held_directory.st_dev, held_directory.st_ino) != (
            named_directory.st_dev, named_directory.st_ino
        ):
            raise SshKeyPreparationError("project root changed during open")
        old = _read_project_leaf(directory_fd, destination_name)
        if expected_old_identity is not None and (
            old is None or old[1] != expected_old_identity
        ):
            raise SshKeyPreparationError("held project public-key identity changed")
        old_data = old[0] if old else b""
        old_identity = _identity(old_data) if old_data else None
        if old_identity == new_identity:
            print(f"[SKIP] project public key already matches: {destination_name}")
            return project / destination_name
        if old_identity is not None and on_mismatch == "reject":
            raise SshKeyPreparationError(
                f"project public key mismatch: {destination_name} source={source} "
                f"old={_fingerprint(old_identity)} new={_fingerprint(new_identity)}; "
                "existing real key was not changed"
            )

        stage_name = f".{destination_name}.{secrets.token_hex(16)}.tmp"
        stage_fd = os.open(
            stage_name, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
            0o644, dir_fd=directory_fd,
        )
        os.fchmod(stage_fd, 0o644)
        view = memoryview(source_data)
        while view:
            written = os.write(stage_fd, view)
            if written <= 0:
                raise SshKeyPreparationError("short project public-key write")
            view = view[written:]
        os.fsync(stage_fd)
        staged = os.fstat(stage_fd)
        rebound_directory = os.lstat(project)
        if (rebound_directory.st_dev, rebound_directory.st_ino) != (
            held_directory.st_dev, held_directory.st_ino
        ):
            raise SshKeyPreparationError("project root rebound before publication")
        rebound = _read_project_leaf(directory_fd, destination_name)
        if (rebound[1] if rebound else None) != (old[1] if old else None):
            raise SshKeyPreparationError("project public-key leaf rebound before publication")
        if (rebound[0] if rebound else b"") != old_data:
            raise SshKeyPreparationError("project public-key content changed before publication")
        rebound_source = os.lstat(source)
        if (rebound_source.st_dev, rebound_source.st_ino, rebound_source.st_mtime_ns) != (
            source_stat.st_dev, source_stat.st_ino, source_stat.st_mtime_ns
        ):
            raise SshKeyPreparationError("source public key changed before publication")
        os.replace(stage_name, destination_name, src_dir_fd=directory_fd, dst_dir_fd=directory_fd)
        stage_name = None
        os.fsync(directory_fd)
        published = os.stat(destination_name, dir_fd=directory_fd, follow_symlinks=False)
        if (published.st_dev, published.st_ino) != (staged.st_dev, staged.st_ino):
            raise SshKeyPreparationError("published project public key rebound")
        old_fingerprint = _fingerprint(old_identity) if old_identity else "absent/empty"
        print(
            f"[CHANGE] {destination_name}: source={source} "
            f"old={old_fingerprint} new={_fingerprint(new_identity)}"
        )
        return project / destination_name
    except OSError as exc:
        raise SshKeyPreparationError(f"project public-key publication failed: {exc}") from exc
    finally:
        if stage_fd >= 0:
            os.close(stage_fd)
        if stage_name is not None and directory_fd >= 0:
            try:
                os.unlink(stage_name, dir_fd=directory_fd)
            except FileNotFoundError:
                pass
        if directory_fd >= 0:
            os.close(directory_fd)
